const obfuscatedMap = {
  "3mfe2r": "BQADAQADXQoAAhZKuEVOnNXJbLlawxYE",
  "58x1a3": "BQADAQADzAoAAhZKuEXDUaRrRaD5ThYE",
  "zlfm3d": "BQADAQAECwACFkq4RYxW1xmlIYuOFgQ",
  "m64m0x": "BQADAQADDgsAAhZKuEXyM9KXt0nyZBYE",
  "j5jmy5": "BQADAQAD_wwAAsvjwUVzfiHNssmleBYE",
  "umuvm8": "BQADAQADkQ0AAsvjwUWUuxI1HNyWSRYE",
  "9r665e": "BQADAQADmQ0AAsvjwUWPftUZFFSt0hYE",
  "yt9io9": "BQADAQADxwsAAsvjyUXrrIDENVQzEBYE",
  "yehyaa": "BQADAQAD4QwAAsvjyUXxf9zAN5ZySxYE",
  "dlpm56": "BQADAQAD-AwAAsvjyUUgHzVetTI1AxYE",
  "6zae23": "BQADAQADCw0AAsvjyUXhh9OPcJjBnhYE",
  "us3f0d": "BQADAQADhgoAAsvj0UWd1E4gmDX0_xYE",
  "n2gimq": "BQADAQAD5QoAAsvj0UWlcMsoW9kH3xYE",
  "kva49w": "BQADAQADJwsAAjdu0UWgYECNw-aGrxYE",
  "onvdhd": "BQADAQADRwsAAjdu0UXeNjNmPFrsDhYE",
  "tg8ho3": "BQADAQADNg0AAjdu2UU3Br0J2T4MFhYE",
  "g9jeud": "BQADAQADcw0AAjdu2UUxinRBoKHa-BYE",
  "2gr2r4": "BQADAQAD2Q0AAjdu2UVmZ4zqqh5JFxYE",
  "zdo1rx": "BQADAQADSQgAAjdu4UWk8wRcQojdWxYE",
  "7wg06j": "BQADAQADZggAAjdu4UVosq4d9D9VhxYE",
  "7uhdey": "BQADAQADjAgAAjdu4UWNYK-e5BMUkBYE",
  "9bgnko": "BQADAQADKAwAAu8X4EWxYHEo3CShphYE",
  "ie1zjp": "BQADAQADUwwAAu8X4EWPZFZSchJouBYE",
  "nepi0f": "BQADAQADmxwAAu8X4EXox7Y75Z5CZhYE",
  "uine7i": "BQADAQADcR0AAu8X4EXTQYMYTgkUAhYE"
};